singleuser:
  image:
    # You should replace the image and the "latest" tag with a fixed version from:
    # https://hub.docker.com/r/jupyter/
    name: jupyter/tensorflow-notebook
    tag: latest
  memory:
    limit: 1.4G
    guarantee: 1G